quanlyvatut/Controllers/back-end/ReportController.cs
using quanlyvatut.DAL;
using quanlyvatut.Models.back_end;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace quanlyvatut.Controllers.back_end
{
    public class ReportController : Controller
    {
        vattudbcontext db = new vattudbcontext();
        //
        // GET: /Report/
        public ActionResult baocaonhap()
        {

            ViewBag.Date = DateTime.Now.ToShortDateString();
            var a = DateTime.Now.Date;
            var query = from i in db.phieunhaps
                        where i.ngaytaophieu == a
                        select i;
            return View(query.ToList());

        }


        [Authorize]
        public ActionResult baocaoxuat()
        {

            ViewBag.Date = DateTime.Now.ToShortDateString();
            var a = DateTime.Now.Date;
            var query = from i in db.phieuxuats
                        where i.ngaytaophieu == a
                        select i;
            return View(query.ToList());

        }
        [Authorize]
        public ActionResult baocaochung()
        {
            ViewBag.countnhap = db.phieunhaps.Count();
            ViewBag.countxuat = db.phieuxuats.Count();
            var grandtotalnhap = db.phieunhaps.AsEnumerable().Sum(s => s.totalprice);
            ViewBag.totalnhap = grandtotalnhap;
            var grandtotalxuat = db.phieuxuats.AsEnumerable().Sum(s => s.totalprice);
            ViewBag.totalxuat = grandtotalxuat;
            var data = db.vattus.Where(q => q.soluong < 5).ToList();
            return View(data);
        }
        public ActionResult _indexvt()
        {
            var data = db.vattus.ToList();
            return PartialView("_indexvt", data);
        }
    }
}

quanlyvatut/Controllers/back-end/qlnhapController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using quanlyvatut.Models.back_end;
using quanlyvatut.DAL;

namespace quanlyvatut.Controllers.back_end
{
    public class qlnhapController : Controller
    {
        private vattudbcontext db = new vattudbcontext();

        // GET: /qlnhap/
        [Authorize(Roles="Admin")]
        public ActionResult Index()
        {
            return View(db.nhaps.ToList());
        }

        // GET: /qlnhap/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nhap nhap = db.nhaps.Find(id);
            if (nhap == null)
            {
                return HttpNotFound();
            }
            return View(nhap);
        }

        // GET: /qlnhap/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /qlnhap/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="id,maphieu,name,day,creator")] nhap nhap)
        {
            if (ModelState.IsValid)
            {
                db.nhaps.Add(nhap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhap);
        }

        // GET: /qlnhap/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nhap nhap = db.nhaps.Find(id);
            if (nhap == null)
            {
                return HttpNotFound();
            }
            return View(nhap);
        }

        // POST: /qlnhap/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="id,maphieu,name,day,creator")] nhap nhap)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhap).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhap);
        }

        // GET: /qlnhap/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nhap nhap = db.nhaps.Find(id);
            if (nhap == null)
            {
                return HttpNotFound();
            }
            return View(nhap);
        }

        // POST: /qlnhap/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            nhap nhap = db.nhaps.Find(id);
            db.nhaps.Remove(nhap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

quanlyvatut/Controllers/back-end/qlvattuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using quanlyvatut.Models.back_end;
using quanlyvatut.DAL;
using PagedList;

namespace quanlyvatut.Controllers.back_end
{
    public class qlvattuController : Controller
    {
        private vattudbcontext db = new vattudbcontext();

        // GET: /qlvattu/
        [Authorize]
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var vattu = from s in db.vattus
                        select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                vattu = vattu.Where(s => s.name.Contains(searchString)
                                       || s.mavattu.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    vattu = vattu.OrderBy(s => s.name);
                    break;
                case "Date":
                    vattu = vattu.OrderByDescending(s => s.ngaytao);
                    break;
                default:  // Name ascending 
                    vattu = vattu.OrderBy(s => s.id);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(vattu.ToPagedList(pageNumber, pageSize));
        }

        // GET: /qlvattu/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vattu vattu = db.vattus.Find(id);
            if (vattu == null)
            {
                return HttpNotFound();
            }
            return View(vattu);
        }

        // GET: /qlvattu/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /qlvattu/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,mavattu,name,soluong,dongia,ngaytao")] vattu vattu)
        {
            if (ModelState.IsValid)
            {
                db.vattus.Add(vattu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vattu);
        }

        // GET: /qlvattu/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vattu vattu = db.vattus.Find(id);
            if (vattu == null)
            {
                return HttpNotFound();
            }
            return View(vattu);
        }

        // POST: /qlvattu/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,mavattu,name,soluong,dongia,ngaytao")] vattu vattu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vattu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vattu);
        }

        // GET: /qlvattu/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vattu vattu = db.vattus.Find(id);
            if (vattu == null)
            {
                return HttpNotFound();
            }
            return View(vattu);
        }

        // POST: /qlvattu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            vattu vattu = db.vattus.Find(id);
            db.vattus.Remove(vattu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

quanlyvatut/Controllers/back-end/qlxuatController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using quanlyvatut.Models.back_end;
using quanlyvatut.DAL;

namespace quanlyvatut.Controllers.back_end
{
    public class qlxuatController : Controller
    {
        private vattudbcontext db = new vattudbcontext();

        // GET: /qlxuat/
        [Authorize]
        public ActionResult Index()
        {
            return View(db.xuats.ToList());
        }

        // GET: /qlxuat/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            xuat xuat = db.xuats.Find(id);
            if (xuat == null)
            {
                return HttpNotFound();
            }
            return View(xuat);
        }

        // GET: /qlxuat/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /qlxuat/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="id,maphieu,name,day,creator")] xuat xuat)
        {
            if (ModelState.IsValid)
            {
                db.xuats.Add(xuat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(xuat);
        }

        // GET: /qlxuat/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            xuat xuat = db.xuats.Find(id);
            if (xuat == null)
            {
                return HttpNotFound();
            }
            return View(xuat);
        }

        // POST: /qlxuat/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="id,maphieu,name,day,creator")] xuat xuat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(xuat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(xuat);
        }

        // GET: /qlxuat/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            xuat xuat = db.xuats.Find(id);
            if (xuat == null)
            {
                return HttpNotFound();
            }
            return View(xuat);
        }

        // POST: /qlxuat/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            xuat xuat = db.xuats.Find(id);
            db.xuats.Remove(xuat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

quanlyvatut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Bootstrap theme</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("QL Nhập", "Index", "qlnhap")</li>
                    <li>@Html.ActionLink("QL Xuất", "Index", "qlxuat")</li>
                    <li>@Html.ActionLink("QL Phiếu Nhập", "Index", "qlphieunhap")</li>
                    <li>@Html.ActionLink("QL Phiếu Xuất", "Index", "qlphieuxuat")</li>
                    <li>@Html.ActionLink("QL Vật Tư", "Index", "qlvattu")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Thống kê <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Báo cáo nhập", "baocaonhap", "Report")</li>
                            <li>@Html.ActionLink("Báo cáo xuất", "baocaoxuat", "Report")</li>
                            <li>@Html.ActionLink("Báo cáo chung","baocaochung","Report")</li>
                        </ul>
                    </li>
                </ul>
            @Html.Partial("_LoginPartial")
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

quanlyvatut/Views/Shared/_LayoutFront-end.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Bootswatch: United</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link href="~/Content/mystyle.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/custom.min.css" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../bower_components/html5shiv/dist/html5shiv.js"></script>
      <script src="../bower_components/respond/dest/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a href="../" class="navbar-brand">Bootswatch</a>
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/workPN/Index">Thao tác phiếu nhập</a>
                    </li>
                    <li>
                        <a href="/workPX/Index">Thao tác phiếu xuất</a>
                    </li>
                    <li>
                        <a href="/workHT/Index">Xem hàng tồn kho</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                   <li> <a href="/Account/Login">Đăng nhập</a>
                    </li>
                </ul>

            </div>
        </div>
    </div>


    <div class="container">
        @RenderBody()
    </div>



    <script src="~/Content/js/jquery.min.js"></script>

    <script src="~/Content/js/bootstrap.min.js"></script>

    <script src="~/Content/js/custom.min.js"></script>
</body>
</html>