quanlyvatut/Controllers/back-end/ReportController.cs
using quanlyvatut.DAL;
using quanlyvatut.Models.back_end;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace quanlyvatut.Controllers.back_end
{
    public class ReportController : Controller
    {
        vattudbcontext db = new vattudbcontext();
        //
        // GET: /Report/
        public ActionResult baocaonhap()
        {

            ViewBag.Date = DateTime.Now.ToShortDateString();
            var a = DateTime.Now.Date;
            var query = from i in db.phieunhaps
                        where i.ngaytaophieu == a
                        select i;
            return View(query.ToList());

        }


        [Authorize]
        public ActionResult baocaoxuat()
        {

            ViewBag.Date = DateTime.Now.ToShortDateString();
            var a = DateTime.Now.Date;
            var query = from i in db.phieuxuats
                        where i.ngaytaophieu == a
                        select i;
            return View(query.ToList());

        }
        [Authorize]
        public ActionResult baocaochung()
        {
            ViewBag.countnhap = db.phieunhaps.Count();
            ViewBag.countxuat = db.phieuxuats.Count();
            var grandtotalnhap = db.phieunhaps.AsEnumerable().Sum(s => s.totalprice);
            ViewBag.totalnhap = grandtotalnhap;
            var grandtotalxuat = db.phieuxuats.AsEnumerable().Sum(s => s.totalprice);
            ViewBag.totalxuat = grandtotalxuat;
            var data = db.vattus.Where(q => q.soluong < 5).ToList();
            return View(data);
        }
        public ActionResult _indexvt()
        {
            var data = db.vattus.ToList();
            return PartialView("_indexvt", data);
        }
    }
}

quanlyvatut/Controllers/back-end/qlphieunhapController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using quanlyvatut.Models.back_end;
using quanlyvatut.DAL;
using PagedList;

namespace quanlyvatut.Controllers.back_end
{
    public class qlphieunhapController : Controller
    {
        vattudbcontext db = new vattudbcontext();

        // GET: /qlphieunhap/
        [Authorize]
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var pn = from s in db.phieunhaps
                     select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                pn = pn.Where(s => s.nhap.maphieu.Contains(searchString)
                                       || s.vattu.name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    pn = pn.OrderBy(s => s.vattuID);
                    break;
                case "Date":
                    pn = pn.OrderByDescending(s => s.ngaytaophieu);
                    break;
                default:  // Name ascending 
                    pn = pn.OrderBy(s => s.id);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(pn.ToPagedList(pageNumber, pageSize));
        }

        // GET: /qlphieunhap/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            phieunhap phieunhap = db.phieunhaps.Find(id);
            if (phieunhap == null)
            {
                return HttpNotFound();
            }
            return View(phieunhap);
        }

        // GET: /qlphieunhap/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.nhapID = new SelectList(db.nhaps, "id", "maphieu");
            ViewBag.vattuID = new SelectList(db.vattus, "id", "name");
            return View();
        }

        // POST: /qlphieunhap/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,nhapID,vattuID,soluong,dongia,ngaytaophieu")] phieunhap phieunhap)
        {
            if (ModelState.IsValid)
            {
                var query = from i in db.vattus
                            where i.id == phieunhap.vattuID
                            select i;
                foreach (vattu i in query)
                {
                    i.soluong = i.soluong + phieunhap.soluong;
                }
                try
                {
                    db.SaveChanges();
                }
                catch (Exception)
                {
                    return HttpNotFound();
                }
                db.phieunhaps.Add(phieunhap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.nhapID = new SelectList(db.nhaps, "id", "maphieu", phieunhap.nhapID);
            ViewBag.vattuID = new SelectList(db.vattus, "id", "name", phieunhap.vattuID);
            return View(phieunhap);
        }

        // GET: /qlphieunhap/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            phieunhap phieunhap = db.phieunhaps.Find(id);
            if (phieunhap == null)
            {
                return HttpNotFound();
            }
            ViewBag.nhapID = new SelectList(db.nhaps, "id", "maphieu", phieunhap.nhapID);
            ViewBag.vattuID = new SelectList(db.vattus, "id", "name", phieunhap.vattuID);
            return View(phieunhap);
        }

        // POST: /qlphieunhap/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nhapID,vattuID,soluong,dongia,ngaytaophieu")] phieunhap phieunhap)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phieunhap).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.nhapID = new SelectList(db.nhaps, "id", "maphieu", phieunhap.nhapID);
            ViewBag.vattuID = new SelectList(db.vattus, "id", "name", phieunhap.vattuID);
            return View(phieunhap);
        }

        // GET: /qlphieunhap/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            phieunhap phieunhap = db.phieunhaps.Find(id);
            if (phieunhap == null)
            {
                return HttpNotFound();
            }
            return View(phieunhap);
        }

        // POST: /qlphieunhap/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            phieunhap phieunhap = db.phieunhaps.Find(id);
            db.phieunhaps.Remove(phieunhap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

quanlyvatut/Controllers/back-end/qlphieuxuatController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using quanlyvatut.Models.back_end;
using quanlyvatut.DAL;
using PagedList;

namespace quanlyvatut.Controllers.back_end
{
    public class qlphieuxuatController : Controller
    {
        private vattudbcontext db = new vattudbcontext();

        // GET: /qlphieuxuat/
        [Authorize]
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var px = from s in db.phieuxuats
                     select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                px = px.Where(s => s.xuat.maphieu.Contains(searchString)
                                       || s.vattu.name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    px = px.OrderBy(s => s.vattuID);
                    break;
                case "Date":
                    px = px.OrderByDescending(s => s.ngaytaophieu);
                    break;
                default:  // Name ascending 
                    px = px.OrderBy(s => s.id);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(px.ToPagedList(pageNumber, pageSize));
        }

        // GET: /qlphieuxuat/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            phieuxuat phieuxuat = db.phieuxuats.Find(id);
            if (phieuxuat == null)
            {
                return HttpNotFound();
            }
            return View(phieuxuat);
        }

        // GET: /qlphieuxuat/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.vattuID = new SelectList(db.vattus, "id", "mavattu");
            ViewBag.xuatID = new SelectList(db.xuats, "id", "maphieu");
            return View();
        }

        // POST: /qlphieuxuat/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,xuatID,vattuID,soluong,dongia,ngaytaophieu")] phieuxuat phieuxuat)
        {

            if (ModelState.IsValid)
            {
                var set = db.vattus.FirstOrDefault(s => s.id == phieuxuat.vattuID);
                if (set.soluong >= phieuxuat.soluong)
                {
                    var query = from i in db.vattus
                                where i.id == phieuxuat.vattuID
                                select i;

                    foreach (vattu i in query)
                    {
                        i.soluong = i.soluong - phieuxuat.soluong;
                    }
                    try
                    {
                        db.SaveChanges();
                    }
                    catch (Exception)
                    {
                        return HttpNotFound();
                    }
                    db.phieuxuats.Add(phieuxuat);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }




                ViewBag.vattuID = new SelectList(db.vattus, "id", "mavattu", phieuxuat.vattuID);
                ViewBag.xuatID = new SelectList(db.xuats, "id", "maphieu", phieuxuat.xuatID);
                return View(phieuxuat);
            }

            return JavaScript("<script language='text/javascript'>alert('Số lượng yêu cầu ko phù hợp');</script>");
        }

        // GET: /qlphieuxuat/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            phieuxuat phieuxuat = db.phieuxuats.Find(id);
            if (phieuxuat == null)
            {
                return HttpNotFound();
            }
            ViewBag.vattuID = new SelectList(db.vattus, "id", "mavattu", phieuxuat.vattuID);
            ViewBag.xuatID = new SelectList(db.xuats, "id", "maphieu", phieuxuat.xuatID);
            return View(phieuxuat);
        }

        // POST: /qlphieuxuat/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,xuatID,vattuID,soluong,dongia,ngaytaophieu")] phieuxuat phieuxuat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phieuxuat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.vattuID = new SelectList(db.vattus, "id", "mavattu", phieuxuat.vattuID);
            ViewBag.xuatID = new SelectList(db.xuats, "id", "maphieu", phieuxuat.xuatID);
            return View(phieuxuat);
        }

        // GET: /qlphieuxuat/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            phieuxuat phieuxuat = db.phieuxuats.Find(id);
            if (phieuxuat == null)
            {
                return HttpNotFound();
            }
            return View(phieuxuat);
        }

        // POST: /qlphieuxuat/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            phieuxuat phieuxuat = db.phieuxuats.Find(id);
            db.phieuxuats.Remove(phieuxuat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

quanlyvatut/Views/qlphieuxuat/Create.cshtml
@model quanlyvatut.Models.back_end.phieuxuat

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>phieuxuat</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.xuatID, "Mã phiếu xuất", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("xuatID", String.Empty)
                @Html.ValidationMessageFor(model => model.xuatID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vattuID, "Mã vật tư", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("vattuID", String.Empty)
                @Html.ValidationMessageFor(model => model.vattuID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soluong, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soluong)
                @Html.ValidationMessageFor(model => model.soluong)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dongia, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dongia)
                @Html.ValidationMessageFor(model => model.dongia)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ngaytaophieu, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaytaophieu)
                @Html.ValidationMessageFor(model => model.ngaytaophieu)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

quanlyvatut/Views/qlphieuxuat/Delete.cshtml
@model quanlyvatut.Models.back_end.phieuxuat

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>phieuxuat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.vattu.mavattu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vattu.mavattu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.xuat.maphieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.xuat.maphieu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soluong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soluong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dongia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dongia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

quanlyvatut/Views/qlphieuxuat/Details.cshtml
@model quanlyvatut.Models.back_end.phieuxuat

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>phieuxuat</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.vattu.mavattu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vattu.mavattu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.xuat.maphieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.xuat.maphieu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soluong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soluong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dongia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dongia)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ngaytaophieu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaytaophieu)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

quanlyvatut/Views/qlphieuxuat/Edit.cshtml
@model quanlyvatut.Models.back_end.phieuxuat

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>phieuxuat</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.xuatID, "Mã phiếu xuất", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("xuatID","Chọn mã phiếu xuất")
                @Html.ValidationMessageFor(model => model.xuatID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.vattuID, "Tên vật tư", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("vattuID","Chọn vật tư")
                @Html.ValidationMessageFor(model => model.vattuID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soluong, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soluong)
                @Html.ValidationMessageFor(model => model.soluong)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dongia, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dongia)
                @Html.ValidationMessageFor(model => model.dongia)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ngaytaophieu, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaytaophieu)
                @Html.ValidationMessageFor(model => model.ngaytaophieu)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

quanlyvatut/Views/qlphieuxuat/Index.cshtml
@model PagedList.IPagedList<quanlyvatut.Models.back_end.phieuxuat>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@using (Html.BeginForm("Index", "qlphieunhap", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Mã phiếu xuất
        </th>
        <th>
            Mã vật tư
        </th>
        <th>
            Số lượng
        </th>
        <th>
            Đơn giá
        </th>
        <th>
            Ngày tạo phiếu
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.xuat.maphieu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.vattu.mavattu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.soluong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dongia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ngaytaophieu)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
@Html.Action("_indexvt","Report")